apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: pyspark-word-count
  namespace: spark-app
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: pyspark-word-count:latest
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///opt/spark/app/main.py
  sparkVersion: 3.5.5
  sparkConf:
    spark.kubernetes.executor.podNamePrefix: word-count
  driver:
    cores: 1
    memory: 512m
    serviceAccount: spark-operator-spark
    securityContext:
      capabilities:
        drop:
        - ALL
      runAsGroup: 185
      runAsUser: 185
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
  executor:
    instances: 2
    cores: 1
    memory: 512m
    securityContext:
      capabilities:
        drop:
        - ALL
      runAsGroup: 185
      runAsUser: 185
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault