apiVersion: spark.apache.org/v1alpha1
kind: SparkApplication
metadata:
  name: pyspark-word-count
  namespace: spark-app
spec:
  pyFiles: "local:///opt/spark/app/main.py"
  sparkConf:
    spark.dynamicAllocation.enabled: "true"
    spark.dynamicAllocation.maxExecutors: "2"
    spark.kubernetes.authenticate.driver.serviceAccountName: "spark"
    spark.kubernetes.file.upload.path: "/workspaces/spark-on-k8s/tmp"
    spark.kubernetes.container.image: "pyspark-word-count:latest"
  applicationTolerations:
    resourceRetainPolicy: OnFailure
  runtimeVersions:
    sparkVersion: "3.5.5"